services:
  mod_auth_openidc:
    build:
      context: ".."
      dockerfile: "docker/mod_auth_openidc.dockerfile"
      args:
#        mod_auth_openidc: "https://github.com/OpenIDC/mod_auth_openidc.git"
#        mod_auth_openidc: "https://github.com/psteniusubi/mod_auth_openidc.git"
        mod_auth_openidc: "."
    image: "local/mod_auth_openidc"
    container_name: "mod_auth_openidc"
    command:
      - "/usr/bin/true"
  httpd-jwks:
    build:
      context: "."
      dockerfile: "httpd.dockerfile"
    image: "local/httpd"
    container_name: "httpd-jwks"
    command:
      - "httpd-foreground"
      - "-f"
      - "./conf-jwks/httpd.conf"
    depends_on:
      - "mod_auth_openidc"
    ports:
      - 443:443
  httpd-jwk:
    build:
      context: "."
      dockerfile: "httpd.dockerfile"
    image: "local/httpd"
    container_name: "httpd"
    command:
      - "httpd-foreground"
      - "-f"
      - "./conf-jwk/httpd.conf"
    depends_on:
      - "mod_auth_openidc"
    ports:
      - 443:443
  httpd-metadatadir-jwks:
    build:
      context: "."
      dockerfile: "httpd.dockerfile"
    image: "local/httpd"
    container_name: "httpd-metadatadir-jwks"
    command:
      - "httpd-foreground"
      - "-f"
      - "./conf-jwks/httpd-metadatadir.conf"
    depends_on:
      - "mod_auth_openidc"
    ports:
      - 443:443
  httpd-metadatadir-jwk:
    build:
      context: "."
      dockerfile: "httpd.dockerfile"
    image: "local/httpd"
    container_name: "httpd-metadatadir-jwk"
    command:
      - "httpd-foreground"
      - "-f"
      - "./conf-jwk/httpd-metadatadir.conf"
    depends_on:
      - "mod_auth_openidc"
    ports:
      - 443:443
